' Gambas module file

Public Sub main()
  
  Dim entrada As Boolean
  'iniciar programa...
  
  Dim ControladorAplicacion As New Controlador
  Dim FormularioControlAcceso As New FControlAcceso
  Dim FormularioPrincipal As New FormPrincipal
  Dim falumno As New FormAlumno
  
  'relaciones MODELO VISTA CONTROLADOR
  FormularioControlAcceso.ControladorAplicacion = ControladorAplicacion
  FormularioPrincipal.ControladorAplicacion = ControladorAplicacion
  falumno.ControladorAplicacion = ControladorAplicacion
  
  ControladorAplicacion.controlAcceso = FormularioControlAcceso
  ControladorAplicacion.Fprincipal = FormularioPrincipal
  ControladorAplicacion.falumno = falumno
  
  'inicio usuario/password si no estan definidas
  ControladorAplicacion.comprobarUsuarioPassword()
  
  entrada = ControladorAplicacion.controlAcceso.Showmodal() 
  
  If entrada = True Then 
    'puedo continual con el program
    ControladorAplicacion.fprincipal.Showmodal()
  Endif
  
  'terminar ejecucion del programa
  'anular relaciones entre formularios y clases
  FormularioControlAcceso.ControladorAplicacion = Null
  ControladorAplicacion.controlAcceso = Null
  FormularioPrincipal.ControladorAplicacion = Null
  ControladorAplicacion.fprincipal = Null 
  falumno.ControladorAplicacion = Null
  ControladorAplicacion.falumno = Null
  
  falumno = Null
  FormularioPrincipal = Null
  FormularioControlAcceso = Null
  ControladorAplicacion = Null
  
  Quit
  
End
